### ISSUE TITLE
Readme update for hooks

### ISSUE THREAD

**Issue by jferragut** [4GeeksAcademy/react-hello-webapp-deprecated#9]
Need to update the readme.md to reflect the changes in the most recent pull request.

- Context.Provider and Context.Consumer have been destructured for ease of use and are now imported as `Provider` and `Consumer`
- All Components were changed to Functions to support the use of hooks
- Actions and store work the same, but we changed the way `appContext.js` works
  - instead of class component, we are using function
  - constructor and state replaced by `useState()` hook
  - `componentDidMount()` was replaced by `useEffect({},[])` which will only run at mount thanks to the second parameter

**Comment by jferragut** [comment]
@alesanchezr since we are going into Hacktoberfest, we can tag the repo for this boilerplate and also label this issue as a good first issue.

**Comment by timrodz** [comment]
Hey! Happy to take this on 😊
